//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _04156258.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB15Entities : DbContext
    {
        public DB15Entities()
            : base("name=DB15Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CollectMeals> CollectMeals { get; set; }
        public virtual DbSet<MealsAndDiscount> MealsAndDiscount { get; set; }
        public virtual DbSet<Member> Member { get; set; }
        public virtual DbSet<Restaurant> Restaurant { get; set; }
        public virtual DbSet<Satisfaction> Satisfaction { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
