//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _04156258.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MealsAndDiscount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MealsAndDiscount()
        {
            this.CollectMeals = new HashSet<CollectMeals>();
            this.Satisfaction = new HashSet<Satisfaction>();
        }
    
        public int MealsID { get; set; }
        public string MealsName { get; set; }
        public int MealsPrice { get; set; }
        public string MealsSort { get; set; }
        public string MealsDiscount { get; set; }
        public int RestaurantID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CollectMeals> CollectMeals { get; set; }
        public virtual Restaurant Restaurant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Satisfaction> Satisfaction { get; set; }
    }
}
